### ISSUE TITLE
zram is no longer included by default in Ubuntu 21.10 for Raspberry Pi.

### ISSUE THREAD

**Issue by sailnfool** [systemd/zram-generator#149] opened 2022-01-09 13:46 UTC
See: https://bugs.launchpad.net/ubuntu/+source/zram-config/+bug/1947697

Apparently the zram module (among others) is no longer there by default on 21.10. It can be installed through the linux-modules-extra-raspi

From the release notes:
Various kernel modules have been moved from the linux-modules-raspi package in order to reduce the initramfs size. This results in several applications (most notably Docker, bug 1947601 18) failing due to missing kernel modules. To work around this:
sudo apt install linux-modules-extra-raspi

**Comment by nabijaczleweli** [comment] 2022-01-09 14:09
Provisionally closing as out-of-scope; I don't see what the issue is here: you need a zram-configured kernel. How you obtain it is, by definition, distribution-specific.

Ubuntu 22.04 seems to be providing a package (and, going by it being 0.3.2 like the sid one, it's probably synced from sid), so take it up with your distributor for breaking this on an upgrade, I guess?

**Closed by nabijaczleweli** 2022-01-09 14:09 UTC
