### ISSUE TITLE
Should provide `Cargo.lock` to make builds reproducible

### ISSUE THREAD

**Issue by NickCao** [systemd/zram-generator#172] opened 2023-01-11 11:32 UTC
According to The Cargo Book: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html, as an end product, zram-generator should check `Cargo.lock` into `git`.

**Comment by nabijaczleweli** [comment] 2023-01-11 11:33
Dupe of #72

**Closed by nabijaczleweli** 2023-01-11 11:33 UTC
