### ISSUE TITLE
Mount with specific owner

### ISSUE THREAD

**Issue by BigmenPixel0** [systemd/zram-generator#150] opened 2022-01-23 15:12 UTC
Can I mount /var/cache/my_folder with specific `uid` and `gid`?
```
[zram5]
zram-size = ram
compression-algorithm = zstd
options = nosuid,nodev
fs-type = ext4
mount-point = /var/cache/my_folder
```

**Comment by nabijaczleweli** [comment] 2022-01-23 15:42
The hack described in the README https://github.com/systemd/zram-generator#mount-points applies, just do `chown` instead of/in addition to chmod (I think that's what you're asking, per analogiam w/tmpfs).

Closing as duplicate of #146. I should really polish the half of a systemd patch I have for this.

**Closed by nabijaczleweli** 2022-01-23 15:42 UTC
Labels: question
